---
name: "Build & publish binary"

on:
  push

jobs:
  build-binaries:
    name: Build & publish binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix --extra-experimental-features nix-command --extra-experimental-features flakes build '.#static'

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: dnsip
          path: result/bin/dnsip
          if-no-files-found: error
